"""document versioning and tombstones

Revision ID: 0a96d4380fe4
Revises: 8e0789cea055
Create Date: 2026-08-19 15:47:47.597478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a96d4380fe4'
down_revision: Union[str, Sequence[str], None] = '8e0789cea055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so existing rows get a value; NOT NULL would fail otherwise.
    op.add_column(
        'document',
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
    )
    op.add_column('document', sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document', sa.Column('superseded_by', sa.Uuid(), nullable=True))
    op.create_index('ix_document_live', 'document', ['tenant_id', 'superseded_at'], unique=False)
    op.create_index(op.f('ix_document_superseded_at'), 'document', ['superseded_at'], unique=False)

    # The content-hash constraint must apply to LIVE documents only. As a plain
    # unique constraint it would block re-adding content that was superseded —
    # a document reverted to a previous revision could never be ingested again.
    op.drop_constraint('uq_document_tenant_hash', 'document', type_='unique')
    op.create_index(
        'uq_document_tenant_hash_live',
        'document',
        ['tenant_id', 'content_hash'],
        unique=True,
        postgresql_where=sa.text('superseded_at IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_document_tenant_hash_live', table_name='document')
    op.create_unique_constraint(
        'uq_document_tenant_hash', 'document', ['tenant_id', 'content_hash']
    )
    op.drop_index(op.f('ix_document_superseded_at'), table_name='document')
    op.drop_index('ix_document_live', table_name='document')
    op.drop_column('document', 'superseded_by')
    op.drop_column('document', 'superseded_at')
    op.drop_column('document', 'version')
    # ### end Alembic commands ###
