"""initial schema with tenant isolation

Revision ID: 1fb64d2aaf50
Revises: 
Create Date: 2026-08-19 13:41:02.692730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

from app.core.config import settings


# revision identifiers, used by Alembic.
revision: str = '1fb64d2aaf50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('trace_span',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('span_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token_cost', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trace_span_tenant_id'), 'trace_span', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_trace_span_trace_id'), 'trace_span', ['trace_id'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('allowed_labels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_index(op.f('ix_app_user_tenant_id'), 'app_user', ['tenant_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('labels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'content_hash', name='uq_document_tenant_hash')
    )
    op.create_index(op.f('ix_document_content_hash'), 'document', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_tenant_id'), 'document', ['tenant_id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_chunk_document_ordinal')
    )
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    op.create_index('ix_chunk_embedding_hnsw', 'chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_chunk_tenant_id'), 'chunk', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- Row-Level Security -------------------------------------------------
    # The application already filters every query by tenant_id. RLS is the backstop
    # for when it does not: a forgotten WHERE clause, a hand-written query, a future
    # bug. Without this, tenant isolation is a convention; with it, it is a database
    # guarantee that holds even against SQL the application never intended to run.
    #
    # FORCE is what makes it real. Plain ENABLE exempts the table owner, and the
    # application connects as the owner — so ENABLE alone would protect nobody here.
    for table in ("document", "chunk", "app_user"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        # current_setting(..., true) returns NULL rather than raising when the GUC is
        # unset. NULL::uuid = tenant_id is NULL, never true, so a query that forgot to
        # SET app.tenant_id sees ZERO rows instead of every row. Default-deny by design.
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
            """
        )

    # The role the application connects as at runtime.
    #
    # This is NOT the migration/owner role. The owner is a superuser, and PostgreSQL
    # exempts superusers from RLS unconditionally — rolbypassrls is not something
    # FORCE ROW LEVEL SECURITY can override. An application connecting as the owner
    # would therefore have every policy above silently ignored, which is a tenant
    # isolation failure that no amount of correct policy SQL can fix.
    #
    # NOSUPERUSER NOBYPASSRLS is stated explicitly rather than relied on as a default,
    # because this is the single property the whole isolation guarantee rests on.
    # Password comes from the environment, never from this file — a migration is
    # committed to git, and a literal here would be a secret in version control.
    # Quoted with SQL's own literal quoting rather than string formatting.
    conn = op.get_bind()
    exists = conn.execute(
        sa.text("SELECT 1 FROM pg_roles WHERE rolname = 'app_rw'")
    ).scalar()
    if not exists:
        quoted = conn.execute(
            sa.text("SELECT quote_literal(:pw)"), {"pw": settings.postgres_app_password}
        ).scalar()
        op.execute(f"CREATE ROLE app_rw LOGIN NOSUPERUSER NOBYPASSRLS PASSWORD {quoted}")

    op.execute("GRANT USAGE ON SCHEMA public TO app_rw")
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON tenant, app_user, document, chunk, "
        "trace_span TO app_rw"
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_rw"
    )

    # Read-only role (created in Phase 0) also needs SELECT on the new tables.
    op.execute("GRANT SELECT ON tenant, app_user, document, chunk, trace_span TO app_readonly")


def downgrade() -> None:
    """Downgrade schema."""

    for table in ("document", "chunk", "app_user"):
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_tenant_id'), table_name='chunk')
    op.drop_index('ix_chunk_embedding_hnsw', table_name='chunk', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_document_tenant_id'), table_name='document')
    op.drop_index(op.f('ix_document_content_hash'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_app_user_tenant_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_trace_span_trace_id'), table_name='trace_span')
    op.drop_index(op.f('ix_trace_span_tenant_id'), table_name='trace_span')
    op.drop_table('trace_span')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
