"""connector audit log

Revision ID: 765a221fcf5a
Revises: 930c57ea50f0
Create Date: 2026-08-20 09:07:51.882281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765a221fcf5a'
down_revision: Union[str, Sequence[str], None] = '930c57ea50f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('connector_id', sa.String(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_audit_allowed'), 'connector_audit', ['allowed'], unique=False)
    op.create_index(op.f('ix_connector_audit_connector_id'), 'connector_audit', ['connector_id'], unique=False)
    op.create_index(op.f('ix_connector_audit_tenant_id'), 'connector_audit', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_connector_audit_trace_id'), 'connector_audit', ['trace_id'], unique=False)
    op.create_index(op.f('ix_connector_audit_user_id'), 'connector_audit', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # An audit row names a tenant's queries and their results, so it is tenant
    # data and carries the same database guarantee as every other such table.
    op.execute("ALTER TABLE connector_audit ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE connector_audit FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY connector_audit_tenant_isolation ON connector_audit
        USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
        """
    )
    # INSERT and SELECT only. An audit log the application can UPDATE or DELETE
    # is not an audit log — the whole value is that entries cannot be revised
    # after the fact by the code being audited.
    op.execute("GRANT SELECT, INSERT ON connector_audit TO app_rw")
    op.execute("GRANT SELECT ON connector_audit TO app_readonly")


def downgrade() -> None:
    """Downgrade schema."""

    op.execute("DROP POLICY IF EXISTS connector_audit_tenant_isolation ON connector_audit")
    op.execute("ALTER TABLE connector_audit DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_audit_user_id'), table_name='connector_audit')
    op.drop_index(op.f('ix_connector_audit_trace_id'), table_name='connector_audit')
    op.drop_index(op.f('ix_connector_audit_tenant_id'), table_name='connector_audit')
    op.drop_index(op.f('ix_connector_audit_connector_id'), table_name='connector_audit')
    op.drop_index(op.f('ix_connector_audit_allowed'), table_name='connector_audit')
    op.drop_table('connector_audit')
    # ### end Alembic commands ###
