"""full text search vector on chunk

Revision ID: 8b33c58074d2
Revises: 0a96d4380fe4
Create Date: 2026-08-19 16:07:42.207314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b33c58074d2'
down_revision: Union[str, Sequence[str], None] = '0a96d4380fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=False))
    op.create_index('ix_chunk_search_vector', 'chunk', ['search_vector'], unique=False, postgresql_using='gin')
    # NOTE: autogenerate wanted to replace uq_document_tenant_hash_live with a
    # plain unique constraint, because a partial index is not expressible in the
    # SQLAlchemy model and so looks like drift. Reverting it would block
    # re-ingesting content that had been superseded. Left alone deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_search_vector', table_name='chunk', postgresql_using='gin')
    op.drop_column('chunk', 'search_vector')
    # ### end Alembic commands ###
