"""ingest job table

Revision ID: 930c57ea50f0
Revises: f88c4be5a0fd
Create Date: 2026-08-19 16:41:25.511240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930c57ea50f0'
down_revision: Union[str, Sequence[str], None] = 'f88c4be5a0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('labels', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False, server_default='queued'),
    sa.Column('files_total', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('files_done', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('documents_created', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('chunks_created', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_job_status'), 'ingest_job', ['status'], unique=False)
    op.create_index(op.f('ix_ingest_job_tenant_id'), 'ingest_job', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # ingest_job names a tenant's documents, so it is tenant data and gets the
    # same database guarantee as every other tenant-scoped table.
    op.execute("ALTER TABLE ingest_job ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ingest_job FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY ingest_job_tenant_isolation ON ingest_job
        USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ingest_job TO app_rw")
    op.execute("GRANT SELECT ON ingest_job TO app_readonly")


def downgrade() -> None:
    """Downgrade schema."""

    op.execute("DROP POLICY IF EXISTS ingest_job_tenant_isolation ON ingest_job")
    op.execute("ALTER TABLE ingest_job DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_job_tenant_id'), table_name='ingest_job')
    op.drop_index(op.f('ix_ingest_job_status'), table_name='ingest_job')
    op.drop_table('ingest_job')
    # ### end Alembic commands ###
