"""agent run records

Revision ID: fe6983226c3f
Revises: 24e06b6f5a57
Create Date: 2026-08-20 11:57:15.138802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6983226c3f'
down_revision: Union[str, Sequence[str], None] = '24e06b6f5a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('halted_reason', sa.Text(), nullable=True),
    sa.Column('steps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tool_call_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('denied_tool_calls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Float(), server_default='0', nullable=False),
    sa.Column('routed_directly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_tenant_id'), 'agent_run', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_run_thread_id'), 'agent_run', ['thread_id'], unique=True)
    op.create_index(op.f('ix_agent_run_trace_id'), 'agent_run', ['trace_id'], unique=False)
    op.create_index(op.f('ix_agent_run_user_id'), 'agent_run', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # LangGraph's checkpoint tables carry no tenant_id and sit outside RLS.
    # THIS table is what closes that gap: it maps a thread to its owner, has a
    # policy, and is consulted before any checkpoint is touched.
    op.execute("ALTER TABLE agent_run ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE agent_run FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY agent_run_tenant_isolation ON agent_run
        USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
        """
    )
    op.execute("GRANT SELECT, INSERT, UPDATE ON agent_run TO app_rw")
    op.execute("GRANT SELECT ON agent_run TO app_readonly")


def downgrade() -> None:
    """Downgrade schema."""

    op.execute("DROP POLICY IF EXISTS agent_run_tenant_isolation ON agent_run")
    op.execute("ALTER TABLE agent_run DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_run_user_id'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_trace_id'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_thread_id'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_tenant_id'), table_name='agent_run')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
