"""The agent graph.

The ONLY file that imports LangGraph. Everything it wires together — planning,
tool invocation, routing — is an ordinary function over our own `AgentState`, so
replacing the framework means rewriting this file and nothing else (ADR 0005).

    plan ──> act ──┐
      ↑            │
      └────────────┘
      │
      └──> end   (answer produced, or a limit hit)

The loop is bounded by our own `RunBudget` rather than by LangGraph's recursion
limit. A framework's own ceiling protects the framework; it knows nothing about
dollars, and the recursion cap is a backstop rather than the control.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from functools import partial
from typing import Any

from langgraph.graph import END, START, StateGraph

from app.agent.limits import RunBudget, RunLimits
from app.agent.nodes import act_node, plan_node, should_continue
from app.agent.state import AgentState, ToolCall
from app.core.security import Principal
from app.llm.base import LLMProvider
from app.tools.base import ToolRegistry


@dataclass(frozen=True)
class AgentRun:
    """The outcome of one run."""

    question: str
    answer: str | None
    halted_reason: str | None
    tool_calls: tuple[ToolCall, ...]
    steps: int
    cost_usd: float
    thread_id: str

    @property
    def succeeded(self) -> bool:
        return self.answer is not None


def build_graph(
    *,
    principal: Principal,
    registry: ToolRegistry,
    llm: LLMProvider,
    budget: RunBudget,
    checkpointer: Any = None,
) -> Any:
    """Compile a graph bound to one caller and one budget.

    Bound per run rather than shared, because the Principal is not serialisable
    and must not be. Re-deriving identity from a verified token on every run is
    what stops a resumed checkpoint carrying authority across a permission
    change — a stored Principal would be a snapshot of what someone could do
    when the run started.
    """
    graph = StateGraph(AgentState)

    graph.add_node(
        "plan",
        partial(plan_node, principal=principal, registry=registry, llm=llm, budget=budget),
    )
    graph.add_node(
        "act",
        partial(act_node, principal=principal, registry=registry, budget=budget),
    )

    graph.add_edge(START, "plan")
    graph.add_conditional_edges("plan", should_continue, {"act": "act", "end": END})
    # Unconditional: after a tool runs, the planner decides what the result
    # means. Routing straight to an answer here would mean the model never sees
    # what it asked for.
    graph.add_edge("act", "plan")

    return graph.compile(checkpointer=checkpointer)


def run_agent(
    question: str,
    *,
    principal: Principal,
    registry: ToolRegistry,
    llm: LLMProvider,
    limits: RunLimits | None = None,
    checkpointer: Any = None,
    thread_id: str | None = None,
) -> AgentRun:
    """Answer a question, choosing tools as needed.

    `thread_id` is server-generated by default and never accepted from a
    request. LangGraph's checkpoint tables key on it and carry no tenant_id, so
    Row-Level Security does not protect them — a caller who could choose a
    thread id could read another tenant's run state. Ownership is resolved from
    our own tables before a checkpoint is ever touched (ADR 0005).
    """
    budget = RunBudget(limits=limits or RunLimits())
    thread = thread_id or str(uuid.uuid4())

    compiled = build_graph(
        principal=principal,
        registry=registry,
        llm=llm,
        budget=budget,
        checkpointer=checkpointer,
    )

    initial: AgentState = {"question": question, "tool_calls": []}
    config = {
        "configurable": {"thread_id": thread},
        # A backstop only. Our budget stops the run long before this, and a
        # framework limit that fired first would produce an error naming
        # recursion rather than the ceiling the operator actually set.
        "recursion_limit": (budget.limits.max_steps * 2) + 4,
    }

    try:
        final: AgentState = compiled.invoke(initial, config=config)
    except Exception as exc:  # noqa: BLE001 — a framework failure must not escape as-is
        # Includes LangGraph's own recursion error. Reported as a halt rather
        # than raised: a run that stopped is an outcome, not a server fault.
        return AgentRun(
            question=question,
            answer=None,
            halted_reason=f"The run stopped unexpectedly ({type(exc).__name__}).",
            tool_calls=(),
            steps=budget.steps,
            cost_usd=round(budget.cost_usd, 6),
            thread_id=thread,
        )

    calls = tuple(ToolCall.from_dict(raw) for raw in final.get("tool_calls", []))

    return AgentRun(
        question=question,
        answer=final.get("answer") or None,
        halted_reason=final.get("halted_reason") or None,
        tool_calls=calls,
        steps=budget.steps,
        cost_usd=round(budget.cost_usd, 6),
        thread_id=thread,
    )
